argument_index:
    path:     /
    defaults: { _controller: bi.argument.controller:indexAction }
    methods:  GET

argument_edit:
    path:     /{id}/edit
    defaults: { _controller: bi.argument.controller:editAction }
    methods:  [GET, POST]

argument_new:
    path:     /new
    defaults: { _controller: bi.argument.controller:newAction }
    methods:  [GET, POST]