user_role_index:
    path:     /
    defaults: { _controller: "BiBundle:UserRole:index" }
    methods:  GET

user_role_show:
    path:     /{id}/show
    defaults: { _controller: "BiBundle:UserRole:show" }
    methods:  GET

user_role_new:
    path:     /new
    defaults: { _controller: "BiBundle:UserRole:new" }
    methods:  [GET, POST]

user_role_edit:
    path:     /{id}/edit
    defaults: { _controller: "BiBundle:UserRole:edit" }
    methods:  [GET, POST]

user_role_delete:
    path:     /{id}/delete
    defaults: { _controller: "BiBundle:UserRole:delete" }
    methods:  DELETE
