imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: '%node_bin%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: '%uglifyjs_bin%'
        uglifycss:
            bin: '%uglifycss_bin%'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'Form'
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - '@BiBundle/Resources/views/form/theme/bootstrap_3_horizontal_layout.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        application_name: "%project_name%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        entity_listener_resolver: bi.doctrine.entity_listener_resolver
        mappings:
            translatable:
                type: annotation
                is_bundle: false
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%redis_server%"
            logging: %kernel.debug%
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis_server%/1"
            options:
                profile: 2.2
                connection_timeout: 10
                read_write_timeout: 30
        session:
            type: predis
            alias: session
            dsn: "redis://%redis_server%/2"
        cluster:
            type: predis
            alias: cluster
            dsn:
                - "redis://%redis_server%/3?weight=10"
                - "redis://%redis_server%/4?weight=5"
                - "redis://%redis_server%/5?weight=1"
    session:
        client: session
        prefix: "%project_name%"
        locking: false

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        user_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                auto_rotate: ~
    loaders:
            upload_files:
                filesystem:
                    data_root: %kernel.root_dir%/../web

doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongodb_host%:%mongodb_port%
            options: {}
    default_database: isup_%kernel.environment%
    document_managers:
        default:
            auto_mapping: true
    auto_generate_hydrator_classes: true

gregwar_captcha:
    width: 200
    height: 50
    length: 6,
    background_color: [255, 255, 255]
    as_url: true
    reload: true
    invalid_message: 'Введен неверный код картинки'

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        empty_content: 204
        exception_wrapper_handler: ApiBundle\Handler\ApiExceptionWrapperHandler
#        view_response_listener: force
    service:
        view_handler: api.view_handler
    disable_csrf_role: ROLE_API
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
#    body_converter:
#        enabled: true
#        validate: true
#        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    format_listener:
        enabled: true
        rules:
          - { path: '^/api/v1', fallback_format: 'json' }
          - { path: '^/', fallback_format: 'html' }
#    unauthorized_challenge: "Basic realm=\"Restricted Area\""
    access_denied_listener:
        json: true
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'ApiBundle\Security\BadCredentialsException': 403
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    # these options are available in 2nd version of bundle
#    zone:
#        - { path: ^/api/* }
#    versioning: true

nelmio_api_doc:
    name: Bi Shop API
    swagger:
        info:
            title: API
            description: Bi Shop API
        api_version:  1
        api_base_path: /api/v1
        swagger_version: '2.0'

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Bi Migrations