api_security:
    type: rest
    prefix: 'auth'
    resource: "ApiBundle\\Controller\\SecurityController"
api_user:
    type: rest
    resource: "ApiBundle\\Controller\\UserController"
api_representation:
    type: rest
    resource: "ApiBundle\\Controller\\ChartController"
api_dashboard:
    type: rest
    resource: "ApiBundle\\Controller\\DashboardController"
api_purchase:
    type: rest
    resource: "ApiBundle\\Controller\\PurchaseController"
api_activation:
    type: rest
    resource: "ApiBundle\\Controller\\ActivationController"
api_card:
    type: rest
    resource: "ApiBundle\\Controller\\CardController"
api_resource:
    type: rest
    resource: "ApiBundle\\Controller\\ResourceController"
api_dashboard_card:
    type: rest
    resource: "ApiBundle\\Controller\\DashboardActivationController"
api_config:
    type: rest
    resource: ApiBundle\Controller\ConfigController
api_activation_settings:
    type: rest
    resource: api.activation_setting.controller