services:
    api.data_transfer_object.user_transfer_object:
        class: ApiBundle\Service\DataTransferObject\UserTransferObject
        arguments: ['@repository.user_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.representation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\RepresentationTransferObject
    api.data.transfer_object.argument_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ArgumentTransferObject
    api.data.transfer_object.resource_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ResourceTransferObject
        arguments: ['@repository.resource_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data_transfer_object.dashboard_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardTransferObject
        arguments: ['@repository.dashboard_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.card_transfer_object:
        class: ApiBundle\Service\DataTransferObject\CardTransferObject
        arguments: ['@api.data.transfer_object.argument_transfer_object', '@api.data.transfer_object.representation_transfer_object', '@utils.host_based_url', '@bi.card.service']
    api.data.transfer_object.purchase_transfer_object:
        class: ApiBundle\Service\DataTransferObject\PurchaseTransferObject
        arguments: ['@api.data.transfer_object.card_transfer_object']
    api.data.transfer_object.activation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ActivationTransferObject
        arguments: ['@repository.activation_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.dashboard_activation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardActivationTransferObject
        arguments: ['@repository.dashboard_activation_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.activation_setting_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ActivationSettingTransferObject
    api.data.transfer_object.card_category_transfer_object:
        class: ApiBundle\Service\DataTransferObject\CardCategoryTransferObject