services:
    api.data_transfer_object.user_transfer_object:
        class: ApiBundle\Service\DataTransferObject\UserTransferObject
        arguments: ['@repository.user_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data_transfer_object.dashboard_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardTransferObject
        arguments: ['@repository.dashboard_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.card_transfer_object:
        class: ApiBundle\Service\DataTransferObject\CardTransferObject
        arguments: ['@repository.card_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.purchase_transfer_object:
        class: ApiBundle\Service\DataTransferObject\PurchaseTransferObject
        arguments: ['@repository.purchase_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.dashboard_card_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardCardTransferObject
        arguments: ['@repository.dashboard_card_repository', '@bi.user_aware_service', '@utils.host_based_url']