services:
    api.data_transfer_object.user_transfer_object:
        class: ApiBundle\Service\DataTransferObject\UserTransferObject
        arguments: ['@repository.user_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.representation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\RepresentationTransferObject
        arguments: ['@repository.representation_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.argument_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ArgumentTransferObject
        arguments: ['@repository.argument_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.resource_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ResourceTransferObject
        arguments: ['@repository.resource_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data_transfer_object.dashboard_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardTransferObject
        arguments: ['@repository.dashboard_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.card_transfer_object:
        class: ApiBundle\Service\DataTransferObject\CardTransferObject
        arguments: ['@repository.card_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.purchase_transfer_object:
        class: ApiBundle\Service\DataTransferObject\PurchaseTransferObject
        arguments: ['@repository.purchase_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.activation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\ActivationTransferObject
        arguments: ['@repository.activation_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.dashboard_activation_transfer_object:
        class: ApiBundle\Service\DataTransferObject\DashboardActivationTransferObject
        arguments: ['@repository.dashboard_activation_repository', '@bi.user_aware_service', '@utils.host_based_url']
    api.data.transfer_object.ui_element_transfer_object:
        class: ApiBundle\Service\DataTransferObject\UiElementTransferObject