services:
    bi.argument.controller:
        class: BiBundle\Controller\ArgumentController
        arguments: ['@bi.argument.service']
        calls:
            - [setContainer, ['@service_container']]
    bi.filter_type.controller:
        class: BiBundle\Controller\FilterTypeController
        arguments: ['@bi.filter_type.service']
        calls:
            - [setContainer, ['@service_container']]
    bi.card.controller:
        class: BiBundle\Controller\CardController
        arguments: ['@bi.card.service']
        calls:
            - [setContainer, ['@service_container']]