services:
    bi.argument.controller:
        class: BiBundle\Controller\ArgumentController
        arguments: ['@bi.argument.service']
        calls:
            - [setContainer, ['@service_container']]
    bi.filter_control_type.controller:
        class: BiBundle\Controller\FilterControlTypeController
        arguments: ['@bi.filter_control_type.service']
        calls:
            - [setContainer, ['@service_container']]