services:
    repository.user_repository:
        class: BiBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\User
    repository.dashboard_repository:
        class: BiBundle\Repository\DashboardRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Dashboard
    repository.card_repository:
        class: BiBundle\Repository\CardRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Card
    repository.representation_repository:
        class: BiBundle\Repository\RepresentationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Representation
    repository.argument_repository:
        class: BiBundle\Repository\ArgumentRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Argument
    repository.activation_repository:
        class: BiBundle\Repository\ActivationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Activation
    repository.resource_repository:
        class: BiBundle\Repository\ResourceRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Resource
    repository.purchase_repository:
        class: BiBundle\Repository\PurchaseRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\Purchase
    repository.dashboard_activation_repository:
        class: BiBundle\Repository\DashboardActivationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - BiBundle\Entity\DashboardActivation
    repository.activation_setting_repository:
            class: BiBundle\Repository\ActivationSettingRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - BiBundle\Entity\ActivationSetting