<?php

namespace BiBundle\Repository;

/**
 * ArgumentFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArgumentFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
