<?php

namespace BiBundle\Repository;

/**
 * CardCarouselImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardCarouselImageRepository extends \Doctrine\ORM\EntityRepository
{
}
