<?php

namespace BiBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    public function create($file)
    {
        $this->_em->persist($file);
        $this->_em->flush($file);
    }
}
