<?php

namespace BiBundle\Repository;

/**
 * FilterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
