<?php

namespace BiBundle\Repository;

/**
 * FilterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Fetches next sort value
     *
     * @return mixed
     */
    public function nextSortValue()
    {
        return $this->getEntityManager()->createQueryBuilder()->select('MAX(f.sort)')
            ->from('BiBundle:FilterType', 'f')
            ->getQuery()->getSingleScalarResult() + 10;
    }
}
