<?php

namespace BiBundle\Repository;

/**
 * FilterControlTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilterControlTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
