BiBundle\Entity\Activation:
    type: entity
    table: activation
    repositoryClass: BiBundle\Repository\ActivationRepository
    indexes:
        activation_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
    manyToOne:
        card:
            targetEntity: Card
            cascade: {  }
            mappedBy: null
            inversedBy: activation
            joinColumns:
                card_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: activation
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        activation_status:
            targetEntity: ActivationStatus
            cascade: {  }
            mappedBy: null
            inversedBy: activation
            joinColumns:
                activation_status_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
