BiBundle\Entity\ActivationStatus:
    type: entity
    table: activation_status
    indexes:
        activation_status_code_idx:
            columns:
                - code
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Название статуса'
        code:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
