BiBundle\Entity\Activation:
    type: entity
    table: activation
    repositoryClass: BiBundle\Repository\ActivationRepository
    indexes:
        activation_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
        loadDataRespond:
            type: text
            nullable: true
            comment: 'META загруженных данных'
            column: load_data_respond
        lastFilter:
            type: text
            nullable: true
            comment: 'Последний актуальный фильтр'
            column: last_filter
    oneToMany:
        resource:
            targetEntity: Resource
            mappedBy: activation
            cascade: ["persist"]
            inversedBy: null
            orphanRemoval: false
    manyToOne:
        card:
            targetEntity: Card
            joinColumns:
                card_id:
                    nullable: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: activation
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
        activation_status:
            targetEntity: ActivationStatus
            joinColumns:
                activation_status_id:
                    nullable: false
    lifecycleCallbacks: {  }
