BiBundle\Entity\Argument:
    type: entity
    table: argument
    gedmo:
        translation:
            locale: locale
    repositoryClass: BiBundle\Repository\ArgumentRepository
    indexes:
        argument_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            comment: 'Наименование аргумента'
            column: name
            gedmo:
              - translatable
        description:
            type: string
            nullable: true
            comment: 'Описание аргумента'
            column: description
            gedmo:
              - translatable
        code:
            type: string
            nullable: false
            comment: 'Аббревиатура аргумента'
            column: code
        dimension:
            type: string
            nullable: true
            comment: 'Ось аргумента'
            column: dimension
        datatype:
            type: string
            nullable: true
            comment: 'Тип данных аргумента'
            column: datatype
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
    manyToOne:
        card:
            targetEntity: BiBundle\Entity\Card
            inversedBy: argument
            joinColumns:
                card_id:
                    referencedColumnName: id
                    nullable: false
    manyToMany:
        argumentFilters:
            targetEntity: BiBundle\Entity\ArgumentFilter
            inversedBy: arguments
            joinTable:
                name: arguments_to_arguments_filters
                joinColumns:
                    argument_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    argument_filter_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
