BiBundle\Entity\ArgumentBond:
    type: entity
    table: argument_bond
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tableName:
            type: string
            nullable: false
            comment: 'Наименование таблицы'
            column: table_name
        columnName:
            type: string
            nullable: false
            comment: 'Уникальное наименование столбца'
            column: column_name
    manyToOne:
        argument:
            targetEntity: BiBundle\Entity\Argument
            cascade: {  }
            mappedBy: null
            inversedBy: bonds
            joinColumns:
                argument_id:
                    referencedColumnName: id
                    nullable: true
                    onDelete: CASCADE
            orphanRemoval: false
        resource:
            targetEntity: BiBundle\Entity\Resource
            cascade: {  }
            mappedBy: null
            inversedBy: bonds
            joinColumns:
                resource_id:
                    referencedColumnName: id
                    nullable: true
                    onDelete: CASCADE
            orphanRemoval: false
        activation:
            targetEntity: BiBundle\Entity\Activation
            cascade: {  }
            mappedBy: null
            inversedBy: bonds
            joinColumns:
                activation_id:
                    referencedColumnName: id
                    nullable: true
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
