BiBundle\Entity\ArgumentFilter:
    type: entity
    table: null
    repositoryClass: BiBundle\Repository\ArgumentFilterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
    manyToOne:
        filterControlType:
            targetEntity: BiBundle\Entity\FilterControlType
            joinColumns:
                filter_control_type_id:
                    referencedColumnName: id
        card:
            targetEntity: BiBundle\Entity\Card
            inversedBy: argumentFilters
            joinColumns:
                card_id:
                    referencedColumnName: id
                    nullable: false
    manyToMany:
        arguments:
            targetEntity: BiBundle\Entity\Argument
            mappedBy: argumentFilters
    lifecycleCallbacks: {  }
