BiBundle\Entity\CardCategory:
    type: entity
    table: card_category
    gedmo:
        translation:
            locale: locale
    repositoryClass: BiBundle\Repository\CardCategoryRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Наименование'
            gedmo:
              - translatable
        path:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Изображение'
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
    oneToMany:
        card:
            targetEntity: Card
            mappedBy: cardCategory
    lifecycleCallbacks: {  }
