BiBundle\Entity\Card:
    type: entity
    table: card
    gedmo:
        translation:
            locale: locale
    repositoryClass: BiBundle\Repository\CardRepository
    indexes:
        card_type_idx:
            columns:
              - type
        card_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Наименование'
            gedmo:
              - translatable
        description:
            type: string
            nullable: true
            length: 2048
            fixed: false
            comment: 'Описание короткое'
            gedmo:
              - translatable
        description_long:
            type: string
            nullable: true
            length: 8192
            fixed: false
            comment: 'Описание полное'
            gedmo:
              - translatable
        rating:
            type: decimal
            nullable: false
            comment: 'Рейтинг в процентах'
            precision: 10
            scale: 2
            default: 0
        author:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Наименование автора'
            gedmo:
              - translatable
        type:
            type: string
            nullable: true
            length: 255
            fixed: false
        price:
            type: decimal
            nullable: false
            comment: 'Стоимость'
            precision: 10
            scale: 2
            gedmo:
              - translatable
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
        data:
            type: json_array
            nullable: true
    oneToMany:
        purchase:
            targetEntity: BiBundle\Entity\Purchase
            mappedBy: card
        cardChart:
            targetEntity: BiBundle\Entity\CardChart
            mappedBy: card
        argument:
            targetEntity: BiBundle\Entity\Argument
            mappedBy: card
            cascade: ["persist"]
            inversedBy: null
            orphanRemoval: false
        cardImage:
            targetEntity: BiBundle\Entity\CardImage
            mappedBy: card
            orderBy: {'priority' : 'ASC'}
        argumentFilters:
            targetEntity: BiBundle\Entity\ArgumentFilter
            mappedBy: card
    manyToOne:
        cardCategory:
            targetEntity: CardCategory
            inversedBy: card
            joinColumns:
                category_id:
                    nullable: true
        image:
                targetEntity: BiBundle\Entity\File
                joinColumns:
                    image_id:
                        nullable: true
    lifecycleCallbacks: {  }
