BiBundle\Entity\CardChart:
    type: entity
    table: card_representation
    indexes:
        card_representation_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
    manyToOne:
        activation:
            targetEntity: Activation
            joinColumns:
                activation_id:
                    nullable: true
        card:
            targetEntity: BiBundle\Entity\Card
            inversedBy: cardChart
            joinColumns:
                card_id:
                    nullable: true
        chart:
            targetEntity: BiBundle\Entity\Chart
            joinColumns:
                chart_id:
                    nullable: true
    lifecycleCallbacks: {  }
