BiBundle\Entity\CardImage:
    type: entity
    table: card_images
    repositoryClass: BiBundle\Repository\CardImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        priority:
            type: integer
            nullable: true
    manyToOne:
        file:
            targetEntity: BiBundle\Entity\File
            inversedBy: cardImage
            joinColumns:
                file_id:
                    nullable: true
        card:
            targetEntity: Card
            inversedBy: cardImage
            joinColumns:
                card_id:
                    nullable: true
    lifecycleCallbacks: {  }
