BiBundle\Entity\FilterType:
    type: entity
    table: filter_control_type
    repositoryClass: BiBundle\Repository\FilterTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
