BiBundle\Entity\FilterType:
    type: entity
    table: filter_types
    repositoryClass: BiBundle\Repository\FilterTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            unique: true
        sort:
            type: integer
            fixed: false
            nullable: false
            options:
                default: 0
    lifecycleCallbacks: {  }
