BiBundle\Entity\Resource:
    type: entity
    table: resource
    repositoryClass: BiBundle\Repository\ResourceRepository
    indexes:
        resource_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
        remoteId:
            type: integer
            nullable: true
            fixed: false
            comment: 'Идентификатор источника данных в платформе BI'
            column: remote_id
        settings:
            type: json_array
            nullable: true
            comment: 'Настройки источника'
    oneToMany:
        bonds:
            targetEntity: BiBundle\Entity\ArgumentBond
            mappedBy: resource
    manyToOne:
        activation:
            targetEntity: Activation
            cascade: {  }
            mappedBy: null
            inversedBy: resource
            joinColumns:
                activation_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: true
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: resource
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
