BiBundle\Entity\Resource:
    type: entity
    table: resource
    indexes:
        resource_create_on_idx:
            columns:
              - created_on
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'Дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'Дата модификации'
            column: updated_on
        platformId:
            type: integer
            nullable: true
            length: 1024
            fixed: false
        path:
            type: string
            nullable: false
            unsigned: false
    manyToOne:
        activation:
            targetEntity: Activation
            cascade: {  }
            mappedBy: null
            inversedBy: resource
            joinColumns:
                activation_id:
                    referencedColumnName: id
                    onDelete: CASCADE
                    nullable: false
            orphanRemoval: false
    lifecycleCallbacks: {  }
